# As of now, we don't use Travis CI to push Docker images.
#
# For one thing, we'd have to build a new image, we don't
# want to use the one that we built using Dockerfile.dev.
#
# We use automated builds on DockerHub.
language: ruby
sudo: required

services:
  - docker

before_install:
  - rake build

script:
  - rake test

after_script:
  - rake rubocop

# https://docs.travis-ci.com/user/notifications
notifications:
  email: false
