language: ruby
sudo: required

services:
  - docker

before_install:
  - rake build

script:
  - rake test

after_script:
  - rake rubocop

# https://docs.travis-ci.com/user/notifications
notifications:
  email: false
